refactor(ci): Splitting CI setup scripts by job (#160)
## [optional body]
This pull request includes several updates to the setup scripts and
GitHub Actions workflows to improve the setup process for various
environments. The most important changes include adding new
dependencies, enhancing the setup scripts with additional checks and
installations, and restructuring the GitHub Actions workflows.

### Setup Script Enhancements:
*
[`.bin/utils/setup_base.sh`](diffhunk://#diff-81e4ae5297dcd81128167750b720017bac32d922a4548af1576ddc088c5c6a22L13-R18):
Added new dependencies such as `sudo`, `tar`, `cmake`, `pkg-config`, and
`protobuf` for both Arch Linux and Ubuntu setups.
*
[`.bin/utils/setup_fish.sh`](diffhunk://#diff-fadcb5fdf5d0234d32af74ae25ec10ec4500a125061829cb11208dbefc107610R34-R46):
Added a check for the `starship` prompt and its installation if not
found.
*
[`.bin/utils/setup_neovim.sh`](diffhunk://#diff-bce54f5d27afd685d28ab4717db16411aca8973ffca420d3e9e5f42fdbc25b7eL34-R34):
Added checks and installations for `ripgrep` and `fd-find` if they are
not found.
[[1]](diffhunk://#diff-bce54f5d27afd685d28ab4717db16411aca8973ffca420d3e9e5f42fdbc25b7eL34-R34)
[[2]](diffhunk://#diff-bce54f5d27afd685d28ab4717db16411aca8973ffca420d3e9e5f42fdbc25b7eR46-R74)

### GitHub Actions Workflow Improvements:
*
[`.github/workflows/main.yml`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L28-R75):
Renamed and restructured jobs to better reflect their purposes, added
caching for system packages, and separated the setup of the base
environment, Rust tools, and other tools into distinct jobs.
[[1]](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L28-R75)
[[2]](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R103-R160)
[[3]](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L102-L105)

### Dependency Management:
*
[`.bin/utils/setup_rust_tools.sh`](diffhunk://#diff-972223cd6df078952acd2c20015c46cb26476e2e12e3d39549014580e8e9c12aL38-R43):
Updated the list of Rust tools by removing `git-delta` and `skim`, and
adding `oxker`.
## [optional footer(s)]

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,10 +25,102 @@ jobs:
         with:
           scandir: '.bin'  # '.bin' ディレクトリ内のシェルスクリプトをチェック
 
- # dotfiles のビルドとテストを行うジョブ
-  build-and-test:
+  setup-base:
     needs: lint  # lint ジョブが成功した後にのみ実行
-    name: Build and Test
+    name: Setup Base Environment
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        container: ['ubuntu:latest', 'archlinux:base-devel']
+        # container: ['ubuntu:latest', 'archlinux:base-devel', 'amazonlinux:2023']
+    container: ${{ matrix.container }}
+    steps:
+    # リポジトリのチェックアウト
+    - uses: actions/checkout@v4
+    - name: Cache system packages
+      uses: actions/cache@v3
+      with:
+        path: |
+          /var/cache/pacman/pkg
+          /var/lib/apt/lists
+        key: ${{ runner.os }}-${{ matrix.container }}-system-packages-${{ hashFiles('.bin/utils/setup_base.sh') }}
+    - name: Set up environment
+      run: |
+        if [ "${{ matrix.container }}" = "archlinux:base-devel" ]; then
+          pacman -Syu --noconfirm
+          pacman -S --noconfirm neovim tmux fish curl git sudo tar cmake pkg-config protobuf
+        else
+          apt-get update
+          apt-get install -y neovim tmux fish curl git build-essential sudo tar cmake
+        fi
+
+    - name: Test Setup base Script
+      run: .bin/utils/setup_base.sh
+
+
+  # ローカルで私用しているRust ツール確認する
+  setup-rust:
+    needs: setup-base
+    name: Test Setup Rust Environment
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        container: ['ubuntu:latest', 'archlinux:base-devel']
+        # container: ['ubuntu:latest', 'archlinux:base-devel', 'amazonlinux:2023']
+    container: ${{ matrix.container }}
+
+    steps:
+
+      # リポジトリのチェックアウト
+    - uses: actions/checkout@v4
+
+      # システムパッケージのキャッシュ
+    - name: Cache system packages
+      uses: actions/cache@v3
+      with:
+        path: |
+          /var/cache/pacman/pkg
+          /var/lib/apt/lists
+        key: ${{ runner.os }}-${{ matrix.container }}-system-packages-${{ hashFiles('.bin/utils/setup_base.sh') }}
+
+      # システムの更新と必要なパッケージのインストール
+    - name: Set up environment
+      run: |
+
+        if [ "${{ matrix.container }}" = "archlinux:base-devel" ]; then
+
+          # Arch Linux
+          pacman -Syu --noconfirm
+          pacman -S --noconfirm neovim tmux fish curl git sudo tar cmake pkg-config protobuf
+
+        else
+          # Ubuntu
+          apt-get update
+          apt-get install -y neovim tmux fish curl git build-essential sudo tar cmake
+
+        fi
+
+    - name: Install Rust
+      shell: bash
+      run: |
+        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+        echo "PATH=$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
+        export PATH="$HOME/.cargo/bin:$PATH"
+        rustc --version || echo "Rust installation failed"
+        cargo --version || echo "Cargo installation failed"
+
+      # セットアップスクリプトの実行
+      # TODO: ここでエラーが出るので、一旦continue-on-errorを設定
+      # これは、gituiがエラーを出すため
+    - name: Test Setup Rust Script
+      run: .bin/utils/setup_rust_tools.sh
+      continue-on-error: true
+
+
+ # dotfiles のビルドとテストを行うジョブ
+  setup-tools:
+    needs: setup-base
+    name: Test Setup Tools
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -67,7 +159,6 @@ jobs:
 
           fi
 
-
       # 依存関係のキャッシュ
       - name: Cache dependencies
         uses: actions/cache@v3
@@ -98,10 +189,6 @@ jobs:
 
       - name: Setup symlinks
         run: .bin/utils/setup_symlinks.sh
-
-      - name: Setup Rust tools
-        run: .bin/utils/setup_rust_tools.sh
-        continue-on-error: true
 
       - name: Setup Neovim
         run: .bin/utils/setup_neovim.sh
